name: efml_client_app
description: "A Flutter project for device management and token authentication."
# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  fl_chart: ^0.69.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Uncomment if you are using assets
  # assets:
  #   - images/logo.png
  #   - images/background.jpg
  # Uncomment if you are using custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
